// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateTokensByUserId(ctx context.Context, arg CreateTokensByUserIdParams) (CreateTokensByUserIdRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error)
	GetTokensByUserId(ctx context.Context, userID uuid.UUID) (UsersCredential, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByUserID(ctx context.Context, id uuid.UUID) (User, error)
	UpdateTokensByUserId(ctx context.Context, arg UpdateTokensByUserIdParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
