-- -- Создание аккаунта пользователя в внешнем сервисе
-- -- name: CreateAccount :one
-- INSERT INTO accounts (user_id, provider_id, provider_user_id, display_name, email, created_at, updated_at)
-- VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
-- RETURNING id;
-- -- name: CreateAccountsCredential :one
-- INSERT INTO accounts_credentials (account_id, access_token, refresh_token, expires_at, created_at)
-- VALUES ($1, $2, $3, $4, $5)
-- RETURNING account_id;
