// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Account struct {
	ID             uuid.UUID      `json:"id"`
	UserID         uuid.UUID      `json:"user_id"`
	ProviderID     int32          `json:"provider_id"`
	ProviderUserID string         `json:"provider_user_id"`
	DisplayName    sql.NullString `json:"display_name"`
	Email          sql.NullString `json:"email"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

type AccountsCredential struct {
	AccountID    uuid.UUID    `json:"account_id"`
	AccessToken  string       `json:"access_token"`
	RefreshToken string       `json:"refresh_token"`
	ExpiresAt    time.Time    `json:"expires_at"`
	EncryptedAt  sql.NullTime `json:"encrypted_at"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}

type Call struct {
	ID           int64                 `json:"id"`
	ProjectID    int64                 `json:"project_id"`
	CallID       string                `json:"call_id"`
	StartedAt    time.Time             `json:"started_at"`
	EndedAt      sql.NullTime          `json:"ended_at"`
	Duration     sql.NullInt32         `json:"duration"`
	Direction    sql.NullString        `json:"direction"`
	Status       sql.NullString        `json:"status"`
	FromNumber   sql.NullString        `json:"from_number"`
	ToNumber     sql.NullString        `json:"to_number"`
	RecordingUrl sql.NullString        `json:"recording_url"`
	Raw          pqtype.NullRawMessage `json:"raw"`
	CreatedAt    sql.NullTime          `json:"created_at"`
}

type EmployeesMetric struct {
	ID          int64                 `json:"id"`
	ProjectID   int64                 `json:"project_id"`
	EmployeeID  string                `json:"employee_id"`
	MetricTime  time.Time             `json:"metric_time"`
	MetricType  string                `json:"metric_type"`
	MetricValue sql.NullFloat64       `json:"metric_value"`
	Payload     pqtype.NullRawMessage `json:"payload"`
	CreatedAt   sql.NullTime          `json:"created_at"`
}

type ExternalProvider struct {
	ID      int32  `json:"id"`
	Service string `json:"service"`
}

type Message struct {
	ID        int64                 `json:"id"`
	ProjectID int64                 `json:"project_id"`
	MessageID string                `json:"message_id"`
	SentAt    sql.NullTime          `json:"sent_at"`
	Sender    sql.NullString        `json:"sender"`
	Recipient sql.NullString        `json:"recipient"`
	Body      sql.NullString        `json:"body"`
	Status    sql.NullString        `json:"status"`
	Raw       pqtype.NullRawMessage `json:"raw"`
	CreatedAt sql.NullTime          `json:"created_at"`
}

type Project struct {
	ID         int64          `json:"id"`
	AccountID  uuid.UUID      `json:"account_id"`
	ShardID    sql.NullInt32  `json:"shard_id"`
	Uuid       uuid.NullUUID  `json:"uuid"`
	Name       string         `json:"name"`
	Subdomain  sql.NullString `json:"subdomain"`
	ShardType  sql.NullInt32  `json:"shard_type"`
	Version    sql.NullInt32  `json:"version"`
	IsKommo    sql.NullBool   `json:"is_kommo"`
	IsTrial    sql.NullBool   `json:"is_trial"`
	TrialEnded sql.NullBool   `json:"trial_ended"`
	IsPayed    sql.NullBool   `json:"is_payed"`
	PayedEnded sql.NullBool   `json:"payed_ended"`
	MfaEnabled sql.NullBool   `json:"mfa_enabled"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
}

type ProjectShard struct {
	ID             int32           `json:"id"`
	Name           string          `json:"name"`
	ConnectionInfo json.RawMessage `json:"connection_info"`
}

type User struct {
	ID           uuid.UUID      `json:"id"`
	Username     string         `json:"username"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	FullName     sql.NullString `json:"full_name"`
	MfaEnabled   sql.NullBool   `json:"mfa_enabled"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}
