// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Создание аккаунта пользователя в внешнем сервисе
	CreateAccount(ctx context.Context, arg CreateAccountParams) (uuid.UUID, error)
	// Создание токенов для этого аккаунта
	CreateAccountCredentials(ctx context.Context, arg CreateAccountCredentialsParams) error
	GetAccountByProviderUserID(ctx context.Context, arg GetAccountByProviderUserIDParams) (GetAccountByProviderUserIDRow, error)
	GetAccountsByUser(ctx context.Context, userID uuid.UUID) ([]GetAccountsByUserRow, error)
	UpdateAccountTokens(ctx context.Context, arg UpdateAccountTokensParams) error
}

var _ Querier = (*Queries)(nil)
